# Generated by Django 3.0.5 on 2020-06-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autofarmapage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caducado',
            fields=[
                ('cantidad', models.BigIntegerField()),
                ('codigo', models.OneToOneField(db_column='codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='cad_codigo', serialize=False, to='autofarmapage.Medicamento')),
            ],
            options={
                'db_table': 'caducado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedidaTiempo',
            fields=[
                ('id_medida_t', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_med_tiempo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medida_tiempo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id_tipo_entrega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_entrega', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_entrega',
                'managed': False,
            },
        ),
    ]
